#1901 add cancel pop up on CNN jobs & summary
rfcx/arbimon pull request #2044
Opened 2024-06-12 09:48 UTC by turk-t

https://github.com/rfcx/arbimon/assets/162116983/61c169ef-8c56-47e0-894a-87ab04d5516d

https://github.com/rfcx/arbimon/assets/162116983/5f647be2-86fe-4d0d-95e5-ae4b3760f6af

2024-06-12 12:06 UTC, grindarius requested changes
I think the modal should have been a separate component that is import-able onto those 2 files.

2024-06-13 10:29 UTC, turk-t commented
> I think the modal should have been a separate component that is import-able onto those 2 files.

Already fix 😀

2024-06-18 05:36 UTC, grindarius approved these changes

2024-06-18 05:36 UTC, grindarius commented on apps/website/src/detect/cnn-job-list/components/cancel-job-modal.vue
> +  if (val === true) {
You can do `if (val)`

2024-06-18 05:53 UTC, merged